namespace: rhjostone
name: dock_pulp_ansible
version: 0.1
readme: README.md
authors:
- Joshua Stone <jostone@redhat.com>
description: Ansible modules for managing dock-pulp repos
license:
- GPL-3.0-or-later
tags:
- packaging
repository: https://github.com/rhjostone/dock_pulp_ansible
documentation: https://github.com/rhjostone/dock_pulp_ansible
homepage: https://github.com/rhjostone/dock_pulp_ansible
issues: https://github.com/rhjostone/dock_pulp_ansible/issues
build_ignore: []
